"""
Property-Based Testing Suite using Hypothesis for AgentTrust Security Framework.
Formally verifies system invariants over randomized, generated parameter domains.
"""

import datetime
import math
import uuid

import pytest

hypothesis = pytest.importorskip("hypothesis")
from hypothesis import given, settings  # noqa: E402
from hypothesis import strategies as st  # noqa: E402

from identity_manager.signature_manager import SignatureManager  # noqa: E402
from server import action_gateway, agent_registry  # noqa: E402

# Generate test agent identity once for fuzzing session
FUZZ_AGENT_ID = "AGENT-PROPERTY-TEST-001"
reg_info = agent_registry.register_agent(FUZZ_AGENT_ID, "PropertyFuzzAgent", "SecurityOps")
AGENT_PRIV_KEY = reg_info["private_key"]

class TestPropertyBasedSecurity:

    @settings(max_examples=50, deadline=1000)
    @given(
        amount=st.one_of(
            st.floats(allow_nan=True, allow_infinity=True),
            st.floats(min_value=-1e9, max_value=-0.01),
            st.text(alphabet="abcdefghijklmnopqrstuvwxyz!@#$%^&*()")
        )
    )
    def test_prop_1_invalid_amounts_always_blocked(self, amount):
        """
        Property Invariant: Any NaN, Infinite, Negative, or Malformed Non-Numeric String amount
        MUST ALWAYS be BLOCKED by the Action Gateway.
        """
        # Filter out valid positive numbers or valid floats if generated by text/floats strategy
        if isinstance(amount, (int, float)):
            if not (math.isnan(amount) or math.isinf(amount) or amount <= 0):
                return
        elif isinstance(amount, str):
            # Check if string parses to a positive float
            try:
                val = float(amount)
                if not (math.isnan(val) or math.isinf(val) or val <= 0):
                    return
            except ValueError:
                pass

        req_id = f"REQ-PROP-{uuid.uuid4().hex[:6]}"
        nonce = f"N-PROP-{uuid.uuid4().hex[:6]}"
        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()

        payload = {
            "request_id": req_id,
            "agent_id": FUZZ_AGENT_ID,
            "action": "CREATE_PURCHASE_ORDER",
            "resource": "SUPPLIER-001",
            "amount": amount,
            "parameters": {"amount": amount},
            "nonce": nonce,
            "timestamp": now_iso
        }

        try:
            sig = SignatureManager.sign_request(payload, AGENT_PRIV_KEY)
            payload["signature"] = sig
        except Exception:
            return

        res = action_gateway.process_request(payload)
        assert res["decision"] == "BLOCKED"
        assert res["reason"] in [
            "INVALID_AMOUNT_NAN_OR_INF",
            "NON_POSITIVE_AMOUNT",
            "INVALID_AMOUNT_FORMAT",
            "AMOUNT_MISMATCH"
        ]

    @settings(max_examples=30, deadline=1000)
    @given(
        top_amt=st.floats(min_value=1.0, max_value=5000.0),
        param_amt=st.floats(min_value=5001.0, max_value=100000.0)
    )
    def test_prop_2_mismatched_top_and_parameter_amounts_blocked(self, top_amt, param_amt):
        """
        Property Invariant: If top-level payload amount differs from parameters['amount'],
        the request MUST ALWAYS be BLOCKED for parameter tampering.
        """
        req_id = f"REQ-PROP-MIS-{uuid.uuid4().hex[:6]}"
        nonce = f"N-PROP-MIS-{uuid.uuid4().hex[:6]}"
        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()

        payload = {
            "request_id": req_id,
            "agent_id": FUZZ_AGENT_ID,
            "action": "CREATE_PURCHASE_ORDER",
            "resource": "SUPPLIER-001",
            "amount": top_amt,
            "parameters": {"amount": param_amt},
            "nonce": nonce,
            "timestamp": now_iso
        }

        sig = SignatureManager.sign_request(payload, AGENT_PRIV_KEY)
        payload["signature"] = sig

        res = action_gateway.process_request(payload)
        assert res["decision"] == "BLOCKED"
        assert res["reason"] == "AMOUNT_MISMATCH"

    @settings(max_examples=30, deadline=1000)
    @given(
        modified_key=st.sampled_from(["request_id", "agent_id", "action", "amount", "timestamp", "nonce"])
    )
    def test_prop_3_tampered_payload_after_signature_always_denied(self, modified_key):
        """
        Property Invariant: Modifying any signed field in the payload after signature creation
        MUST ALWAYS lead to an unbypassable decision of BLOCKED.
        """
        req_id = f"REQ-PROP-SIG-{uuid.uuid4().hex[:6]}"
        nonce = f"N-PROP-SIG-{uuid.uuid4().hex[:6]}"
        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()

        payload = {
            "request_id": req_id,
            "agent_id": FUZZ_AGENT_ID,
            "action": "TRANSFER_FUNDS",
            "resource": "ACC-001",
            "amount": 500.0,
            "parameters": {"amount": 500.0},
            "nonce": nonce,
            "timestamp": now_iso
        }

        sig = SignatureManager.sign_request(payload, AGENT_PRIV_KEY)
        payload["signature"] = sig

        if modified_key == "amount":
            payload["amount"] = 99999.0
            payload["parameters"]["amount"] = 99999.0
        elif modified_key == "request_id":
            payload["request_id"] = f"REQ-FORGED-{uuid.uuid4().hex[:4]}"
        elif modified_key == "agent_id":
            payload["agent_id"] = "AGENT-ROGUE-FORGED"
        elif modified_key == "action":
            payload["action"] = "DELETE_DATABASE"
        elif modified_key == "nonce":
            payload["nonce"] = f"N-FORGED-{uuid.uuid4().hex[:4]}"
        elif modified_key == "timestamp":
            payload["timestamp"] = "2020-01-01T00:00:00Z"

        res = action_gateway.process_request(payload)
        assert res["decision"] == "BLOCKED"
        assert res["reason"] in [
            "INVALID_SIGNATURE",
            "UNKNOWN_AGENT",
            "AMOUNT_MISMATCH",
            "TIMESTAMP_EXPIRED",
            "REPLAY_DETECTED"
        ]

